version: '3'
services:
  database:
    image: mysql:8.0.17
    command:
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mto
    ports:
      - 3309:3306
  app:
    build:
      .
    volumes:
      - .:/var/www/html
    ports:
      - 5002:80
    depends_on:
      - database